### PR TITLE
added support for bigger R(2+1)d

### PR DESCRIPTION
**Pull request by v-iashin**
This PR will track additional changes to #22 by @v-iashin:
- [x] docs
  - [x] credits
  - [x] docs itself
- [ ] update google colab after PR merge
  - [x] add Acc@1, 5 on Kinetics.
  - [x] does mwe still works by default?
- [x] brush up the code
  - [x] check the output for the non-kinetics dataset (is it `400`)

### CODE REVIEW

**Comment by v-iashin** [comment]
@ohjho hey I was going through the PR and wondering what is the performance of `r2plus1d_34_32_kinetics` and `r2plus1d_34_8_kinetics` in terms of Acc@1 and Acc@5 on Kinetics 400. It is optional but I would add this info to Google Colab and docs.

**Comment by ohjho** [comment]
> @ohjho hey I was going through the PR and wondering what is the performance of `r2plus1d_34_32_kinetics` and `r2plus1d_34_8_kinetics` in terms of Acc@1 and Acc@5 on Kinetics 400. It is optional but I would add this info to Google Colab and docs.

from [their paper](https://arxiv.org/pdf/1905.00561.pdf) I can only find top-1 (79.1) and top-5 (93.9) for `r2plus1d_34_32_kinetics`

**Comment by v-iashin** [comment]
I think this PR can now be merged. 

@ohjho, could you check if everything looks good to you (credits, model naming, and .md docs). I am planning to merge it tomorrow the latest.

**Comment by ohjho** [comment]
this looks great @v-iashin

**Comment by ohjho** [comment]
this looks great @v-iashin

**Pull request merged**
